# Generated by Django 3.0.7 on 2020-06-29 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myfooddata',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='Name', max_length=200, null=True)),
                ('food_group', models.CharField(blank=True, db_column='Food_Group', max_length=50, null=True)),
                ('fat', models.DecimalField(blank=True, db_column='Fat', decimal_places=2, max_digits=10, null=True)),
                ('protein', models.DecimalField(blank=True, db_column='Protein', decimal_places=2, max_digits=10, null=True)),
                ('carbohydrate', models.DecimalField(blank=True, db_column='Carbohydrate', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'MyFoodData',
                'managed': False,
            },
        ),
    ]
